require("accme.plugins-setup")
require("accme.plugins.nvim-cmp")
require("accme.core.options")
require("accme.core.keymaps")
require("accme.plugins.fine-cmdline")
require("accme.plugins.comment")
require("accme.plugins.neo-tree")
require("accme.plugins.lualine")
require("accme.plugins.telescope")
require("accme.plugins.lsp.mason")
require("accme.plugins.lsp.lspconfig")
require("accme.plugins.lsp.null-ls")
require("accme.plugins.autopairs")
require("accme.plugins.treesitter")
require("accme.plugins.lsp.go")
require("accme.plugins.lsp.polyglot")
require("accme.plugins.vim-matchup")
require("accme.plugins.nvim-colorizer")
-- smooth scrolling --
require("accme.plugins.neoscroll")

-- THEME --
-- require("accme.themes.starry")
require("accme.themes.gruvbox")
-- require("accme.themes.sonokai")

require("accme.core.colorscheme")
